### **Import Libraries**
This cell imports necessary libraries like pandas for data manipulation, numpy for numerical operations, and seaborn/matplotlib for data visualization.

In [1]:
import pandas as pd;
import numpy as np;
import seaborn as sns;
import matplotlib.pyplot as plt;

### **Load Dataset**
This cell loads the diabetes dataset from a CSV file into a pandas DataFrame and displays the first few rows.

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/Kirisaki00/Ensemble_Techniques-/refs/heads/main/diabetes.csv");
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


### **Separate Features and Target**
Here, the dataset is split into features (x) and the target variable (y), where 'Outcome' is the target.

In [3]:
x=df.drop(columns=["Outcome"], axis=1);
y=df["Outcome"];

### **Split Data into Train, Validation, and Test Sets**
This cell divides the data into training, validation, and test sets for model development and evaluation.

In [27]:
from sklearn.model_selection import train_test_split;
train, val_train, test, val_test=train_test_split(x,y,test_size=0.5, random_state=42)
x_train, x_test, y_train, y_test=train_test_split(train, test, test_size=0.2, random_state=42)

### **Train and Evaluate K-Nearest Neighbors (KNN)**
This cell initializes, trains, and evaluates a K-Nearest Neighbors classifier on the training and test data.

In [28]:
from sklearn.neighbors import KNeighborsClassifier;
knn=KNeighborsClassifier();
knn.fit(x_train, y_train);
knn.score(x_test, y_test)

0.7532467532467533

### **Train and Evaluate Support Vector Machine (SVM)**
This cell initializes, trains, and evaluates a Support Vector Machine classifier.

In [29]:
from sklearn.svm import SVC;
svm=SVC();
svm.fit(x_train,y_train);
svm.score(x_test, y_test)

0.7662337662337663

### **Make Predictions on Validation Set**
This cell generates predictions from both KNN and SVM models on the validation training set.

In [30]:
pred_val1=knn.predict(val_train);
pred_val2=svm.predict(val_train);

### **Display KNN Validation Predictions**
This cell displays the predictions made by the K-Nearest Neighbors model on the validation set.

In [31]:
pred_val1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,

### **Display SVM Validation Predictions**
This cell displays the predictions made by the Support Vector Machine model on the validation set.

In [32]:
pred_val2

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

### **Stack Validation Predictions**
This cell combines the predictions from KNN and SVM models on the validation set into a single array.

In [33]:
pred_val=np.column_stack((pred_val1,pred_val2));
pred_val

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0,

### **Make and Stack Test Predictions**
This cell generates predictions from both models on the test set and stacks them.

In [34]:
pred_test1=knn.predict(x_test);
pred_test2=svm.predict(x_test);
pred_test=np.column_stack((pred_test1,pred_test2));
pred_test

array([[1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0,

### **Train and Evaluate Random Forest (Meta-Learner)**
This cell trains a Random Forest Classifier using the stacked validation predictions as input and evaluates it on the stacked test predictions.

In [36]:
from sklearn.ensemble import RandomForestClassifier;
rf=RandomForestClassifier();
rf.fit(pred_val, val_test);
rf.score(pred_test, y_test)

0.7662337662337663

### **Setup GridSearchCV for Hyperparameter Tuning**
This cell defines the hyperparameter grid for tuning the Random Forest Classifier and initializes GridSearchCV.

In [42]:
from sklearn.model_selection import GridSearchCV;
grid_parameters={
    "n_estimators":[90,100,115],
    "criterion":["gini", "entropy"],
    "min_samples_leaf":[1,2,3,4,5],
    "max_features":[4,5,6,7,8]
};
grid_search=GridSearchCV(estimator=rf, param_grid=grid_parameters, cv=5);

### **Fit GridSearchCV and Get Best Parameters**
This cell executes the grid search to find the best hyperparameters for the Random Forest model based on the validation data.

In [49]:
grid_search.fit(pred_val, val_test);
grid_search.best_params_

{'criterion': 'gini',
 'max_features': 4,
 'min_samples_leaf': 1,
 'n_estimators': 90}

### **Train and Evaluate Random Forest with Tuned Hyperparameters**
This cell trains a new Random Forest Classifier using the best hyperparameters found by GridSearchCV and evaluates its performance on the test set.

In [52]:
from sklearn.ensemble import RandomForestClassifier;
rf=RandomForestClassifier(criterion='gini',max_features= 4,min_samples_leaf=1,n_estimators=90);
rf.fit(pred_val, val_test);
rf.score(pred_test, y_test)

0.7662337662337663